# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWxSaPrtelr6fHgHZMzdXY0l7AjzcYzk
"""

def print_polish_flag():
    print("Task 1 - Polish Flag: \n")

    white = '\033[107m \033[0m'
    red = '\033[41m \033[0m'

    for _ in range(4):
        for _ in range(25):
            print(white, end='')
        print()

    for _ in range(4):
        for _ in range(25):
            print(red, end='')
        print()

def print_pattern():
  print("Task 2 - Print pattern: \n")

  white = '\033[107m \033[0m'
  repetition = 1
  length = 25
  height = 5

  for line in range(height):
      if line % 2 == 0:
          print(white * length * repetition)
      elif line % 5 == 1:
          print((length // 2 * ' ' + white + length // 2 * ' ') * repetition)
      else:
          print((length // 3 * ' ' + white + length // 3 * ' ' + white) * repetition)

def print_sqrt_graph():
    print("Task 3 - Graph of y = √x: \n")

    grid_size = 25
    grid = [[' ' for _ in range(grid_size)] for _ in range(grid_size)]

    for i in range(grid_size):
        grid[grid_size-1][i] = '-'  # x-axis
    grid[grid_size-1][grid_size-1] = '>'

    for i in range(grid_size):
        grid[i][0] = '|'            # y-axis
    grid[0][0] = '^'

    grid[grid_size-1][0] = '+'      # origin

    for x in range(grid_size):
        try:
            y = int((x) ** 0.5)
            if 0 <= y < grid_size and 0 <= x < grid_size:
                grid[grid_size-1-y][x] = '*'
        except:
            pass

    for row in grid:
        print(' '.join(row))

def percentage_diagram():
    with open('sequence.txt', 'r') as file:
        numbers = [float(line.strip()) for line in file]

    firstpart = numbers[:125]
    secondpart = numbers[125:]

    sum_first = sum(abs(x) for x in firstpart)
    sum_second = sum(abs(x) for x in secondpart)

    total = sum_first + sum_second
    percent_first = (sum_first / total) * 100
    percent_second = (sum_second / total) * 100

    bar_length = 40
    bar1 = int((percent_first / 100) * bar_length)
    bar2 = bar_length - bar1

    print('Task 4 - Percentage diagram')
    print(f"First part absolute avg: {sum_first:.2f}")
    print(f"Second part absolute avg: {sum_second:.2f}")
    print(f"Percentage: {percent_first:.1f}% / {percent_second:.1f}%")
    print(f"First 125 numbers: [{(red * bar1) + (white * bar2)}] {percent_first:.1f}%")
    print(f"Second 125 numbers: [{(white * bar1) + (red * bar2)}] {percent_second:.1f}%")

print_polish_flag()
print_pattern()
print_sqrt_graph()
percentage_diagram()

